--- #YAML:1.0
name:               Date-HolidayParser
version:            0.4
abstract:           Parser for .holiday-files
author:
    - Eskild Hustvedt <zerodogg@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    Any::Moose:  0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
